# This file should be listed in .gitignore to keep your settings secret!
REDDIT_USERNAME: myuser
REDDIT_PASSWORD: mypass
REDDIT_SUBREDDIT: mysubreddit
LISTDIGEST_WHITELIST: "test@example.org,test@example.com" 
IP_WHITELIST: "127.0.0.1"
